endpoints:
  prometheus:
    path: "ali-metrics"

management:
  port: 8081
  security:
    enabled: false

srv:
  accesskey: 2SbUQlH7FJKyur9V
  securityKey: WGoQpjLNgTA4VwrHNQBcqe0zDbXZti
  mqPlatform: onsConsole
  mqUrl: http://mq.console.cpct.com.cn/json/consumer/accumulate
  mqRegionId: shihua
  mqConsumerId: CID_CRM_TEST_1206
  mqTopicDetail: true
  rdsFormat: JSON
  rdsVersion: 2014-08-15
  rdsSignatureMethod: HMAC-SHA1
  rdsSignatureVersion: 1.0
  rdsUrl: http://rds.cpct.com.cn
  rdsAction: DescribeSlowLogs
  rdsDBInstanceId: rds2439awoqx0363m0ib
  rdsDBName: test
  