endpoints:
  prometheus:
    path: "ali-metrics"

management:
  port: 8081
  security:
    enabled: false

srv:
  accesskey: 2SbUQlH7FJKyur9V
  securityKey: WGoQpjLNgTA4VwrHNQBcqe0zDbXZti
  mqPlatform: onsConsole
  mqUrl: http://mq.console.cpct.com.cn/json/consumer/accumulate
  mqRegionId: shihua
  mqConsumerId: CID_CRM_TEST_1206
  mqTopicDetail: true
  rdsFormat: JSON
  rdsVersion: 2014-08-15
  rdsSignatureMethod: HMAC-SHA1
  rdsSignatureVersion: 1.0
  rdsUrl: http://rds.cpct.com.cn
  rdsAction: DescribeSlowLogs
  rdsDBInstanceId: rds2439awoqx0363m0ib
  rdsDBName: test
  ## slb配置
  slbFormat: JSON
  slbVersion: 2014-05-15
  slbSignatureMethod: HMAC-SHA1
  slbSignatureVersion: 1.0
  slbUrl: http://slb.cpct.com.cn
  slbAction: DescribeHealthStatus
  slbLoadBalancerId: 161fa5394b3-cn-beijing-zgyz-d01
  slbListenerPort: 80
  ## redis配置
  redisFormat: JSON
  redisVersion: 2015-01-01
  redisSignatureMethod: HMAC-SHA1
  redisslbSignatureVersion: 1.0
  redisUrl: http://kvstore.cpct.com.cn
  redisDescribeInstances: DescribeInstances
  redisDescribeHistoryMonitorValues: DescribeHistoryMonitorValues
  redisInstanceId: 74314bb1fe9c4ecc
  redisIntervalForHistory: 01m
  ## 多个配置
  rdsList:
    - format: JSON
      version: 2014-08-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://rds.cpct.com.cn
    - format: XML
      version: 2099-08-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.1
      url: http://rds.cpct.com.cn