endpoints:
  prometheus:
    path: "ali-metrics"

management:
  port: 8081
  security:
    enabled: false

srv:
  accesskey: 2SbUQlH7FJKyur9V
  securityKey: WGoQpjLNgTA4VwrHNQBcqe0zDbXZti
  ## mq 监控参数 ###
  mqPlatform: onsConsole
  mqUrl: http://mq.console.cpct.com.cn/json/consumer/accumulate
  mqRegionId: shihua
  mqConsumerId: CID_CRM_TEST_1206
  mqTopicDetail: true
  ## edas 监控参数 ###
  edasUrl: http://edas.console.cpct.com.cn/api
  edasLogUrl: http://192.168.248.173:9200/
  edasAction: /app/app_list
  edasLogIndex: edas*
  edasLogTimeRange: 1m
  edasLogMessageKey: exception
  edasLogLevel: ERROR
  ## 多个redis配置 （注：当同一服务配置多个实例数据时，配置项名字需要小写）
  redisList:
    - format: JSON
      version: 2015-01-01
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://kvstore.cpct.com.cn
      descinstances: DescribeInstances
      deschistorymonitorvalues: DescribeHistoryMonitorValues
      instanceid: 74314bb1fe9c4ecc
      interval: 01m
  ## 多个slb配置
  slbList:
    - format: JSON
      version: 2014-05-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://slb.cpct.com.cn
      action: DescribeHealthStatus
      loadbalancerid: 161fa5394b3-cn-beijing-zgyz-d01
      listenerport: 80
    - format: JSON
      version: 2014-05-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://slb.cpct.com.cn
      action: DescribeHealthStatus
      loadbalancerid: 161fa5394b3-cn-beijing-zgyz-d01
      listenerport: 80      
  ## 多个rds配置
  rdsList:
    - format: JSON
      version: 2014-08-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://rds.cpct.com.cn
      action: DescribeSlowLogs
      dbinstanceid: rds2439awoqx0363m0ib
      dbname: test
    - format: JSON
      version: 2014-08-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://rds.cpct.com.cn
      action: DescribeSlowLogs
      dbinstanceid: rds2439awoqx0363m0ib
      dbname: test