endpoints:
  prometheus:
    path: "ali-metrics"

management:
  port: 8081
  security:
    enabled: false

srv:
  accesskey: 2SbUQlH7FJKyur9V
  securityKey: WGoQpjLNgTA4VwrHNQBcqe0zDbXZti
  mqPlatform: onsConsole
  mqUrl: http://mq.console.cpct.com.cn/json/consumer/accumulate
  mqRegionId: shihua
  mqConsumerId: CID_CRM_TEST_1206
  mqTopicDetail: true
  ## redis配置
  redisFormat: JSON
  redisVersion: 2015-01-01
  redisSignatureMethod: HMAC-SHA1
  redisslbSignatureVersion: 1.0
  redisUrl: http://kvstore.cpct.com.cn
  redisDescribeInstances: DescribeInstances
  redisDescribeHistoryMonitorValues: DescribeHistoryMonitorValues
  redisInstanceId: 74314bb1fe9c4ecc
  redisIntervalForHistory: 01m
  ## slb配置
  slbList:
    - format: JSON
      version: 2014-05-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://slb.cpct.com.cn
      action: DescribeHealthStatus
      loadbalancerid: 161fa5394b3-cn-beijing-zgyz-d01
      listenerport: 80
    - format: JSON
      version: 2014-05-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://slb.cpct.com.cn
      action: DescribeHealthStatus
      loadbalancerid: 161fa5394b3-cn-beijing-zgyz-d01
      listenerport: 80      
  ## 多个配置
  rdsList:
    - format: JSON
      version: 2014-08-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://rds.cpct.com.cn
      action: DescribeSlowLogs
      dbinstanceid: rds2439awoqx0363m0ib
      dbname: test
    - format: JSON
      version: 2014-08-15
      signaturemethod: HMAC-SHA1
      signatureversion: 1.0
      url: http://rds.cpct.com.cn
      action: DescribeSlowLogs
      dbinstanceid: rds2439awoqx0363m0ib
      dbname: test